[package]
name = "x-adox-core"
version = "1.0.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
walkdir = { workspace = true }
nom = { workspace = true }
anyhow = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
