[package]
name = "x-adox-core"
version = "2.3.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
walkdir = { workspace = true }
nom = { workspace = true }
anyhow = { workspace = true }
x-adox-bitnet = { path = "../x-adox-bitnet" }
regex = "1.12.2"
directories = "5.0"
serde_json = { workspace = true }
chrono = { workspace = true }
rayon = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
