[package]
name = "x-adox-cli"
version = "2.0.3"
edition = "2021"

[dependencies]
x-adox-core = { workspace = true }
x-adox-bitnet = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
