name: Qodo Merge (PR Agent)

on:
  pull_request:
    types: [opened, reopened, synchronize]
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  issues: write
  contents: read

jobs:
  pr_agent_job:
    if: >
      github.event.sender.type != 'Bot' &&
      (
        (
          github.event_name == 'pull_request' &&
          github.event.pull_request.head.repo.full_name == github.repository
        ) ||
        (
          github.event_name == 'issue_comment' &&
          github.event.issue.pull_request != null &&
          contains(fromJSON('["OWNER", "MEMBER", "COLLABORATOR"]'), github.event.comment.author_association) &&
          (
            startsWith(github.event.comment.body, '/review') ||
            startsWith(github.event.comment.body, '/describe') ||
            startsWith(github.event.comment.body, '/improve') ||
            startsWith(github.event.comment.body, '/ask') ||
            startsWith(github.event.comment.body, '/summarize')
          )
        )
      )
    runs-on: ubuntu-latest
    name: Run PR Agent
    steps:
      - name: PR Agent action
        uses: qodo-ai/pr-agent@d36ad319f7fb0049205017405a71275c41599587
        env:
          OPENAI_KEY: "${{ secrets.OPENAI_KEY }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            pr_url: ${{ github.event.pull_request.html_url || github.event.issue.html_url }}
            command: ${{ github.event.comment.body || '/review' }}
